version: "2"
services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./dist:/server/dist
    ports:
      - "9999:9999"
      - "9222:9222"
  db:
    container_name: move_mongodb
    image: mongo
    ports:
    - "27017:27017"
